name: deploy-auth
on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t nazatmustag/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{DOCKER_PASSWORD}}
      - run: docker push nazatmustag/auth
